# Generated by Django 5.1.3 on 2024-12-28 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_student_id_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
    ]
