# Generated by Django 5.1.4 on 2025-01-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_authorised',
            new_name='is_authorized',
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='CGGwgxmsoBt08YeF6dBPGNhM6g0YCm1K', editable=False, max_length=32, unique=True),
        ),
    ]
