# Generated by Django 5.1.3 on 2025-01-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0002_rename_is_authorised_customuser_is_authorized_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='tt4iQPJyvP7XIMAZQ2DexinMChPMmVbo', editable=False, max_length=32, unique=True),
        ),
    ]
