# Generated by Django 5.1.3 on 2025-01-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0003_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='3MD2p1WRrI5T15OO7Pw7bIym33KNpvnj', editable=False, max_length=32, unique=True),
        ),
    ]
