# Generated by Django 5.1.3 on 2025-01-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0004_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='TaWbU4ETwspVFjLlMKqtpH5TpfbW8LE9', editable=False, max_length=32, unique=True),
        ),
    ]
